config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'pcr#index'
  resources :pcr
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/template.rb
class Template < ActiveRecord::Base

  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def fullname
    self.first_name +""+self.last_name
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pcr_controller.rb
class PcrController < ApplicationController
  before_filter :authenticate_user!, only: [:show ]
  
  def index
    @templates = Template.all.order(title: :desc)
  end
  
  def show
    @template = Template.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pcr_helper.rb
module PcrHelper
end

app/views/layouts/_header.html.erb
<!--- Header start-->
<nav role="navigation" class="navbar navbar-fixed-top header">
  <div class="container">
    <div class="navbar-header">
      <button data-target=".navbar-ex1-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a href=<%= root_url %> class="navbar-brand">Home</a>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<!--- Header end-->  

<div class="clearfix"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pcr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render :partial => "layouts/header"%>
  <div class="container main-container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pcr/_template.html.erb
<%= link_to temp.title, pcr_path(temp), class: "list-group-item" %>


app/views/pcr/index.html.erb
<div class="row">
  <div class="outer-div">
    <div class="list-group">
     <a href="#" class="list-group-item active">
        Email Templates
      </a>
      <hr>
     <% @templates.each do |temp| %>
      <%= render partial: "template", locals: { temp: temp } %>
    <% end %>     
    </div>
  </div>
</div>

app/views/pcr/show.html.erb
<%= javascript_include_tag "pcr" %>
<div class="row">
  <div class="outer-div">
    <div class="list-group">
      <div id = 'template_description'>
        <%= @template.description.html_safe %></br>
      </div>  
      <hr>
      <a href=<%= root_url %> class="left ">
        Back
      </a>
      
      <%= mail_to current_user.email, "USE TEMPLATE", subject: @template.title, body: @template.description.html_safe, id:'mail_to' %>
      
    </div>
  </div>
</div>